return {
    {
        "nvim-treesitter/nvim-treesitter",
        build = ":TSUpdate",
        config = function () 
            local configs = require("nvim-treesitter.configs")

            configs.setup({
                ensure_installed = { 
                    "arduino",
                    "asm",
                    "bash",
                    "bitbake",
                    "c",
                    "c_sharp",
                    "cmake",
                    "cpp",
                    "css",
                    "csv",
                    "devicetree",
                    "diff",
                    "dockerfile",
                    "git_config",
                    "git_rebase",
                    "gitattributes",
                    "gitcommit",
                    "gitignore",
                    "go",
                    "gpg",
                    "groovy",
                    "html",
                    "http",
                    "ini",
                    "java",
                    "javadoc",
                    "javascript",
                    "jinja",
                    "jq",
                    "json",
                    "json5",
                    "kconfig",
                    "latex",
                    "lua",
                    "luadoc",
                    "make",
                    "markdown",
                    "markdown_inline",
                    "nginx",
                    "ninja",
                    "objdump",
                    "ocaml",
                    "passwd",
                    "pem",
                    "perl",
                    "php",
                    "python",
                    "regex",
                    "robot",
                    "ruby",
                    "ssh_config",
                    "tmux",
                    "typescript",
                    "verilog",
                    "vhdl",
                    "vim",
                    "vimdoc",
                    "xml",
                    "yaml",
                    "zig"
                },
            sync_install = false,
            highlight = {
                enable = true,
            },
            indent = { enable = true },  
            })
        end
    }
}